### ISSUE TITLE
Specify the GPU-id in training

### ISSUE THREAD

**Issue by ghost** [idiap/apam#1]
Hi 
Thank you for this great tools!!
Because I don't have the permissions to make gpu in compute-exclusive mode (`nvidia-smi -c 3`), it would get `CUDA out of memory` in training if I set `initial_job>1`.
I fixed this issue in Kaldi by set different `CUDA_VISIBLE_DEVICES` number in different jobs in `steps/libs/nnet3/train/chain_objf/acoustic_model.py`
If I would like to do this thing, where should I rewrite?

I thought it might be in the function `train_lfmmi_one_iteration` ?

**Comment by mrsrikanth** [comment]
Can't you just export the environment variable like below:

```
export CUDA_VISIBLE_DEVICE=...
```

**Comment by ghost** [comment]
I want to make each job is fixed at specific single GPU. 
I thought the reason why "out of memory" is that sometimes the different jobs will compute at same GPU.
If I set `CUDA_VISIBLE_DEVICE` outside the training code, it would not solve the memory issue.

**Comment by mrsrikanth** [comment]
Ok. Can you share how you modify the code in Kaldi to set this? It would help me get a better picture.

**Comment by ghost** [comment]
Sure.
I modified function `train_new_models` from file `steps/libs/nnet3/train/chain_objf/acoustic_model.py`
```
...
for job in range(1, num_jobs+1):
  thread = common_lib.background_command(
  """ CUDA_VISIBLE_DEVICE={i} {command} {train_queue_opt} ...
  nnet3-chain-train ...
  """.format(i=job-1, command=...)
...
)
```

**Comment by mrsrikanth** [comment]
Thanks. In this case, you can just change ``run_train_job`` in ``src/e2e/train.py``, which is the function that launches the job. In this case, the job id ``i`` is available as ``job_id``.

**Comment by ghost** [comment]
Solved by modified the function `run_train_job` from file `src/e2e/train.py`
```
process_out = subprocess.run([...], env={'CUDA_VISIBLE_DEVICE':"{}".format(job_id-1), **os.environ})
```
Thanks!

**Comment by ghost** [comment]
Sorry to reopen this issue
It seems that my modification randomly selected the GPU. So after some iteration it has memory issue again.
Do you have any suggestion?

**Comment by ghost** [comment]
Sorry my fault.
It is `CUDA_VISIBLE_DEVICES`
